version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/home/node/app

